name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Installing nodejs"
        uses: actions/setup-node@v4
      - name: "Installing dependencies"
        run: npm ci
      - name: "Running tests"
        run: sh test-scripts.sh