name: Pull request validation

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "installing nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: "installing dependencies"
        run: npm install
      - name: "running tests"
        run: sh test-script.sh
